version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php grpc-worker.php"
  relay: pipes

grpc:
  listen: tcp://0.0.0.0:9001
  pool:
    num_workers: 4
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s
  proto:
    - "proto/shortener.proto"

logs:
  level: debug
  mode: development
  output: stdout
  err_output: stderr
